# see more about dockerfile templates here:http://docs.resin.io/pages/deployment/docker-templates
FROM resin/%%RESIN_MACHINE_NAME%%-debian

# Set our working directory
WORKDIR /usr/src/app

# Copy all files in our root to the working  directory in the container
 COPY . ./

# Switch on systemd init system in container
ENV INITSYSTEM on

# Run the script to turn off LED lights on the beaglebone black.  Both the heartbeat lights and the power light will go dark.

CMD ["/usr/src/app/lightsout.sh"]
